[versions]
assertk = "0.28.1"
jackson = "2.21.0"
junit-platform = "6.0.1"
jvm = "21"
kotlin = "2.3.0"
ktlint = "14.0.1"
springdoc-openapi = "1.8.0"
versions-plugin = "0.53.0"

[libraries]
assertk = { module = "com.willowtreeapps.assertk:assertk-jvm", version.ref = "assertk" }
fasterxml-core = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
fasterxml-datatype = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8", version.ref = "jackson" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-platform" }
junit-platform-suite = { module = "org.junit.platform:junit-platform-suite", version.ref = "junit-platform" }
springdoc-openapi-ui = { module = "org.springdoc:springdoc-openapi-ui", version.ref = "springdoc-openapi" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions-plugin" }
