[versions]
assertk = "0.28.1"
junit-platform = "6.0.1"
jvm = "21"
kotlin = "2.2.21"
springdoc-openapi = "1.8.0"

[libraries]
assertk = { module = "com.willowtreeapps.assertk:assertk-jvm", version.ref = "assertk" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-platform" }
junit-platform-suite = { module = "org.junit.platform:junit-platform-suite", version.ref = "junit-platform" }
springdoc-openapi-ui = { module = "org.springdoc:springdoc-openapi-ui", version.ref = "springdoc-openapi" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
